### ISSUE TITLE
help

### ISSUE THREAD

**Issue by gedw99** [alexandrestein/gotinydb#2]
Combining badger with bleve for indexing is exactly what i wanted to see.

I would like to help... but have a few high level goal questions:

1. Embedded or server or both ?
- see blast for bleve (https://github.com/mosuka/blast)

2. Works off standard golang structs ? It seems yes ?

3. Query language. It seems the user does not need to compile the queries ?
see this example:
https://github.com/ipfs/go-ds-badger/blob/master/datastore.go
See the query import !

**Comment by alexandrestein** [comment]
I'm happy to hear from you :smile: 

1. for now the database is embedded. There is plenty of dedicated database service out there and I don't plan to compete with those. :smile: 
I thought to use [Bleve](https://github.com/blevesearch/bleve) directly.

2. It is supposed to be used directly with Golang structs.

3. I'm confused with this question. You point to a package which I don't know but I don't see any compile queries.
If you ask if the queries need to be compiled inside [gotinydb](https://github.com/alexandrestein/gotinydb) the queries are "compiled" during the build of the package.
I maybe just missed the question.

Thank you for your interest.

**Comment by gedw99** [comment]
Thats pretty much answers the questions.. Thanks.

Regarding the query language for the IPFS Badger store. It seems they recently changed the import path :)
Here it is now: https://github.com/ipfs/go-datastore/tree/master/query


Are you planning to make it easy to run as a cluster and backup ?
https://github.com/yongman/leto/tree/master/store
- raft for boltdb and badgerdb over grpc.

**Comment by alexandrestein** [comment]
The query system has pretty much the same design as "IPFS Badger Store" but here the filtered are typed.
I don't know this package so can't say with too much confidence.

The cluster mode is not planed for now but it would be a very nice feature.
[Raft](https://raft.github.io/) could be a good tool for this but I need to look much deeper in it to have a stronger point of view. 

The backup is already supported into a ZIP file.

**Comment by gedw99** [comment]
That pretty much answers the bits I was wondering about.

Hopefully some of those libs helped.
